In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('All_Courses_In_Germany.csv',delimiter=';')

In [3]:
pd.set_option('display.max_colwidth', None)

In [4]:
df.sample(1)

,Course ID,Course Name,Course Short Name,Subject Name,University Name,City Name,Teaching languages Instruction,Required German language,Required English language,Beginning,Duration of Programme,Tuition Fees,Course Details Link
660,4677,Expanded Media,Expanded Media,"Performing Arts, Film and Television, Drama",Darmstadt University of Applied Sciences,Dieburg,English,None,None,"Winter semester, Summer semester","3 semesters, 4 semesters",none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4677/

In [5]:
filt=['data analytics','business analytics','data analysis','business intelligence']

In [6]:
da=df[
    (df['Course Name'].str.contains('|'.join(filt),case=False)) &\
    (df['Subject Name'].isin(['Business and Economics','Computer Science']))
  ]
da.head(1)

,Course ID,Course Name,Course Short Name,Subject Name,University Name,City Name,Teaching languages Instruction,Required German language,Required English language,Beginning,Duration of Programme,Tuition Fees,Course Details Link
294,6944,"Business Analytics (BSc), full-time",Business Analytics (BSc),Business and Economics,SRH University of Applied Sciences in North Rhine-Westphalia,Hamm,English,None,None,"Winter semester, Summer semester",6 semesters,4080,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/6944/

In [7]:
da.shape

(17, 13)

## There are 17 courses offered in the field of analytics

In [8]:
da['Required German language'].value_counts()

None    17
Name: Required German language, dtype: int64

## None of the courses in data analytics require german language

In [9]:
df_free=da[~da['Tuition Fees'].str.isdigit()]

In [10]:
len(df_free)

8

## There are only 8 courses in analytics that have zero tuition fees

In [11]:
df_free

,Course ID,Course Name,Course Short Name,Subject Name,University Name,City Name,Teaching languages Instruction,Required German language,Required English language,Beginning,Duration of Programme,Tuition Fees,Course Details Link
302,4529,Business Intelligence and Process Management (MSc),Business Intelligence and Process Management (MSc),Business and Economics,Hochschule für Wirtschaft und Recht Berlin,Berlin,English,None,None,Winter semester,3 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4529/
414,5561,Data Analytics (MSc),Data Analytics (MSc),Computer Science,University of Hildesheim Foundation,Hildesheim,English,None,None,"Winter semester, Summer semester",4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/5561/
1606,8423,Master's in Business Analytics & Econometrics – Master of Science,Master's in Business Analytics & Econometrics – MSc,Business and Economics,University of Cologne,Köln,English,None,None,Winter semester,4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/8423/
1607,8556,Master's in Business Analytics (MSc),Master's in Business Analytics (MSc),Business and Economics,EBS Universität für Wirtschaft und Recht,Oestrich-Winkel,English,None,None,Winter semester,"2 semesters, 4 semesters",None,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/8556/
1755,4407,Medical Engineering – Branches of Study: Medical Image and Data Processing | Health and Medical Data Analytics & Entrepreneurship | Medical Robotics,"Medical Engineering: Imaging, Health & Data Analytics or Robotics",Computer Science,FAU Erlangen-Nürnberg,Erlangen,English,None,None,"Winter semester, Summer semester",4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4407/
1779,8516,MISU at LMU: Big Data Analytics and Business Intelligence (EBI),Big Data Analytics and Business Intelligence (EBI),Business and Economics,Ludwig-Maximilians-Universität München,München,English,None,"B2, C1",None,None,None,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/8516/
1792,5148,MISU at LMU: Machine Learning and Data Analytics in Finance and Accounting (MDA),Machine Learning and Data Analytics,Business and Economics,Ludwig-Maximilians-Universität München,München,English,None,"B2, C1",None,None,None,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/5148/
1907,4777,Operations Research and Business Analytics (ORBA),Operations Research and Business Analytics (ORBA),Business and Economics,Otto von Guericke University Magdeburg,Magdeburg,English,None,None,Winter semester,4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4777/

In [12]:
df_free.drop(columns=['Required German language','Required English language'],inplace=True)

/Users/ayushlingwal/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [13]:
df_free=df_free.reset_index(drop=True)

In [14]:
df_free

,Course ID,Course Name,Course Short Name,Subject Name,University Name,City Name,Teaching languages Instruction,Beginning,Duration of Programme,Tuition Fees,Course Details Link
0,4529,Business Intelligence and Process Management (MSc),Business Intelligence and Process Management (MSc),Business and Economics,Hochschule für Wirtschaft und Recht Berlin,Berlin,English,Winter semester,3 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4529/
1,5561,Data Analytics (MSc),Data Analytics (MSc),Computer Science,University of Hildesheim Foundation,Hildesheim,English,"Winter semester, Summer semester",4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/5561/
2,8423,Master's in Business Analytics & Econometrics – Master of Science,Master's in Business Analytics & Econometrics – MSc,Business and Economics,University of Cologne,Köln,English,Winter semester,4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/8423/
3,8556,Master's in Business Analytics (MSc),Master's in Business Analytics (MSc),Business and Economics,EBS Universität für Wirtschaft und Recht,Oestrich-Winkel,English,Winter semester,"2 semesters, 4 semesters",None,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/8556/
4,4407,Medical Engineering – Branches of Study: Medical Image and Data Processing | Health and Medical Data Analytics & Entrepreneurship | Medical Robotics,"Medical Engineering: Imaging, Health & Data Analytics or Robotics",Computer Science,FAU Erlangen-Nürnberg,Erlangen,English,"Winter semester, Summer semester",4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4407/
5,8516,MISU at LMU: Big Data Analytics and Business Intelligence (EBI),Big Data Analytics and Business Intelligence (EBI),Business and Economics,Ludwig-Maximilians-Universität München,München,English,None,None,None,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/8516/
6,5148,MISU at LMU: Machine Learning and Data Analytics in Finance and Accounting (MDA),Machine Learning and Data Analytics,Business and Economics,Ludwig-Maximilians-Universität München,München,English,None,None,None,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/5148/
7,4777,Operations Research and Business Analytics (ORBA),Operations Research and Business Analytics (ORBA),Business and Economics,Otto von Guericke University Magdeburg,Magdeburg,English,Winter semester,4 semesters,none,https://www2.daad.de/deutschland/studienangebote/international-programmes/en/detail/4777/

In [18]:
df_free.to_csv('/Users/ayushlingwal/Pandas Projects/german uni courses/Data Analytics.csv',index=False)